[package]
name = "extension"
version = "0.1.0"
authors = ["Eric Mertens <emertens@galois.com>"]
build = "build.rs"

[build-dependencies]
bindgen="0.25.1"

[lib]
name = "myextension"
crate-type = ["cdylib"]
